### ISSUE TITLE
Issue with LoginButton

### ISSUE THREAD

**Issue by ixoye36** [finkinfridom/payload-auth0-plugin#211]
Hi

Many thanks for the plugin !!

I believe there is an issue with the REACT_APP_AUTH0_LOGIN_URL use

In the LoginButton file, we find :

`const LoginButton = (props) => {
    return () => {
        const { text = "Log In with SSO", href = process.env.REACT_APP_AUTH0_LOGIN || "/auth0/login", } = props || {};
        return (react_1.default.createElement("a", { className: "btn btn--style-secondary btn--icon-style-without-border btn--size-medium", style: {
                width: "100%",
                display: "block",
            }, href: href }, text));
    };
};`

There is no _URL to the var env, so I keep being led to /auth0/login instead of the url I setup

Also I didn't get from the ReadMe, how to use the your-auth-collection.ts

Thanks !

**Comment by finkinfridom** [comment]
hey @ixoye36 , you're right. I just updated the code to use the proper env variable now.
for the usage, here's the example I have in my local env

```
import { Auth0Strategy, PictureField } from "../src";
export const userCollection = {
  slug: "users",
  fields: [
    {
      name: "picture",
      type: "text",
      admin: {
        hidden: true,
        condition: (data) => {
          return data.picture;
        },
      },
    },
    {
      name: "pictureVisual",
      type: "ui",
      admin: {
        position: "sidebar",
        condition: (_, siblingData) => {
          return siblingData.picture;
        },
        components: {
          Field: PictureField,
          Cell: PictureField,
        },
      },
    },
    {
      name: "sub",
      type: "text",
      admin: {
        readOnly: true,
        condition: (data) => {
          return data.sub;
        },
      },
    },
  ],
  auth: {
    strategies: [
      {
        name: Auth0Strategy.name,
        strategy: (ctx) => {
          return new Auth0Strategy(ctx, "users");
        },
      },
    ],
  },
};

```
where you can see the `auth.strategies` prop is set
