### ISSUE TITLE
about the config

### ISSUE THREAD

**Issue by chaeyan** [finkinfridom/payload-auth0-plugin#67]
maybe try being specific about the urls in the config, like REACT_APP_SERVER_BASE_URL REACT_APP_AUTH0_LOGIN_URL REACT_APP_AUTH0_LOGOUT_URL what are these meant to be? payload's urls? it could be good if you just put example config in readme

**Comment by finkinfridom** [comment]
Thanks for the suggestion. I'll add a bit more documentation ASAP

**Comment by finkinfridom** [comment]
README file update. @chaeyan please have a look
